version: "3"
services:
  selenium-hub:
    restart: always
    image: selenium/hub:latest
    container_name: hub
    ports:
      - "4444:4444"
  chrome:
    restart: always
    image: selenium/node-chrome
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  app:
    image: sspy
    container_name: sspy
    depends_on:
      - chrome
    volumes:
      - .:/app